DROP TABLE IF EXISTS account_groups;
create table account_groups(ssn varchar(40), first_name varchar(40),  last_name varchar(40), group_name varchar(50));
insert into account_groups(ssn, first_name, last_name, group_name) values ('123456789','Thu', 'Lett','Gold');
insert into account_groups(ssn, first_name, last_name, group_name) values ('543987556','Leah', 'Calvo','Silver');
insert into account_groups(ssn, first_name, last_name, group_name) values ('778524395','Boris', 'Fay','Platinum');
insert into account_groups(ssn, first_name, last_name, group_name) values ('125948637','Johana', 'Relyea','Blue');
insert into account_groups(ssn, first_name, last_name, group_name) values ('6544932875','Debi','Winford', 'Silver');
insert into account_groups(ssn, first_name, last_name, group_name) values ('193756824','Vernice', 'Corbin','Gold');
insert into account_groups(ssn, first_name, last_name, group_name) values ('485266791','Perry', '', 'Silver');
insert into account_groups(ssn, first_name, last_name, group_name) values ('5978824631','Bella','Gastelum','Blue');
insert into account_groups(ssn, first_name, last_name, group_name) values ('164959728','Jordon','Polito','Silver');
insert into account_groups(ssn, first_name, last_name, group_name) values ('346596782','Irena','Bach','Blue');
insert into account_groups(ssn, first_name, last_name, group_name) values ('862495377','Ofir','Levy','Gold');
insert into account_groups(ssn, first_name, last_name, group_name) values ('953463735','Mara','Sherrard','Blue');
insert into account_groups(ssn, first_name, last_name, group_name) values ('613249578','Craig','Fullmer','Blue');
insert into account_groups(ssn, first_name, last_name, group_name) values ('555196666','Mary', 'Popkins', 'Gold');
DROP PROCEDURE IF EXISTS move_to_silver;
CREATE PROCEDURE move_to_silver (IN userId VARCHAR(255)) Update account_groups set group_name='Silver' where ssn=userId;
DROP PROCEDURE IF EXISTS move_to_gold;
CREATE PROCEDURE move_to_gold (IN userId VARCHAR(255)) Update account_groups set group_name='Gold' where ssn=userId;
DROP PROCEDURE IF EXISTS move_to_platinum;
CREATE PROCEDURE move_to_platinum (IN userId VARCHAR(255)) Update account_groups set group_name='Platinum' where ssn=userId;