DROP TABLE IF EXISTS SALES;
CREATE TABLE SALES (NAME VARCHAR(20), COMMISSION DECIMAL);
DROP PROCEDURE IF EXISTS UPDT_SALES;
CREATE PROCEDURE UPDT_SALES (IN PARM1 VARCHAR(50), IN PARM2 int) INSERT INTO SALES VALUES (parm1, parm2);